/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package multiproject_demo.utilities

import multiproject_demo.list.LinkedList

class StringUtils {
    static String join(LinkedList source) {
        return JoinUtils.join(source)
    }

    static LinkedList split(String source) {
        return SplitUtils.split(source)
    }
}
