/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package multiproject_demo.app

import multiproject_demo.list.LinkedList

import static multiproject_demo.utilities.StringUtils.join
import static multiproject_demo.utilities.StringUtils.split
import static multiproject_demo.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
